import ApolloClient from 'apollo-client';
import { UseProduct, AdditionalAlliesInfo, BestTeaser } from '../../index';
export declare const useProductPrice: (client: ApolloClient<any>, productContext: UseProduct | null) => {
    client: ApolloClient<any>;
    productContext: UseProduct;
    getListPrice: () => number | null;
    getSellingPrice: () => number | null;
    getBadgeDiscount: () => number | null;
    getBaseDiscount: () => number | null;
    getAlliesDiscount: () => number | null;
    getAlliesDiscountPrice: () => number | null;
    sellers: import("../..").UseSellers;
    clases?: string | undefined;
    getBenefits: () => Promise<AdditionalAlliesInfo[]>;
    getBestTeaser: () => BestTeaser | null;
    parsePrice: (price: number) => number | null;
    currencyOptions: import("../..").CurrencyOptions;
    bestMyDiscount?: number | undefined;
} | null;
export declare const useProductHook: (client: ApolloClient<any>, productContext: UseProduct) => {
    client: ApolloClient<any>;
    productContext: UseProduct;
    getListPrice: () => number | null;
    getSellingPrice: () => number | null;
    getBadgeDiscount: () => number | null;
    getBaseDiscount: () => number | null;
    getAlliesDiscount: () => number | null;
    getAlliesDiscountPrice: () => number | null;
    sellers: import("../..").UseSellers;
    clases?: string | undefined;
    getBenefits: () => Promise<AdditionalAlliesInfo[]>;
    getBestTeaser: () => BestTeaser | null;
    parsePrice: (price: number) => number | null;
    currencyOptions: import("../..").CurrencyOptions;
    bestMyDiscount?: number | undefined;
};
